# Generated by Django 5.1.4 on 2025-01-10 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_split_details_expense_split_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Split Equally'), ('manual', 'Manual Amount Entry'), ('percentage', 'Percentage-Based'), ('ratio', 'Ratio-Based'), ('excess', 'Excess Adjustment')], max_length=50),
        ),
    ]
