# Generated by Django 5.1.4 on 2025-11-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Split Equally'), ('manual', 'Manual Amount Entry'), ('percentage', 'Percentage-Based'), ('ratio', 'Ratio-Based'), ('shares', 'Shares-Based'), ('excess', 'Excess Adjustment'), ('full_owed', 'You are owed full amount'), ('full_owe', 'You owe full amount')], max_length=50),
        ),
    ]
