# Generated by Django 5.1.4 on 2025-01-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_user_expense_added_by_expensesplit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Split Equally'), ('manual', 'Manual Amount Entry'), ('percentage', 'Percentage-Based'), ('ratio', 'Ratio-Based'), ('excess', 'Excess Adjustment')], default='equal', max_length=20),
            preserve_default=False,
        ),
    ]
