# Generated by Django 5.1.4 on 2025-11-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_paid_by_alter_expense_split_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Split Equally'), ('manual', 'Manual Amount Entry'), ('percentage', 'Percentage-Based'), ('ratio', 'Ratio-Based'), ('shares', 'Shares-Based'), ('excess', 'Excess Adjustment')], max_length=50),
        ),
    ]
