# Generated by Django 5.1.4 on 2025-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_expense_updated_at_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='currency',
            field=models.CharField(choices=[('ARS', 'Peso Argentino'), ('UYU', 'Peso Uruguayo'), ('CLP', 'Peso Chileno'), ('MXN', 'Peso Mexicano'), ('BRL', 'Real Brasilero'), ('USD', 'Dolar EEUU'), ('EUR', 'Euro'), ('GBP', 'Libras'), ('JPY', 'Yenes'), ('PYG', 'Guaranies Paraguayos'), ('AUD', 'Dolar Australiano'), ('KRW', 'Won Coreano')], default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('ARS', 'Peso Argentino'), ('UYU', 'Peso Uruguayo'), ('CLP', 'Peso Chileno'), ('MXN', 'Peso Mexicano'), ('BRL', 'Real Brasilero'), ('USD', 'Dolar EEUU'), ('EUR', 'Euro'), ('GBP', 'Libras'), ('JPY', 'Yenes'), ('PYG', 'Guaranies Paraguayos'), ('AUD', 'Dolar Australiano'), ('KRW', 'Won Coreano')], default='ARS', max_length=3),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('settled', 'Settled')], max_length=20),
        ),
    ]
