# Generated by Django 5.1.4 on 2025-12-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Home Supplies', 'Home Supplies'), ('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Periodic Expenses', 'Periodic Expenses'), ('Health', 'Health'), ('Other', 'Other')], max_length=20),
        ),
    ]
